monolog:
  channels: ['member-login', 'customer-login']
  handlers:
    member_login:
      type: fingers_crossed
      action_level: error
      passthru_level: info
      handler: member_login_rotating_file
      channels: [ 'member-login' ]
    member_login_rotating_file:
      type: rotating_file
      max_files: 60
      path: '%kernel.logs_dir%/%kernel.environment%/member-login.log'
      formatter: login.log.formatter.line
      level: debug

    customer_login:
      type: fingers_crossed
      action_level: error
      passthru_level: info
      handler: customer_login_rotating_file
      channels: [ 'customer-login' ]
    customer_login_rotating_file:
      type: rotating_file
      max_files: 60
      path: '%kernel.logs_dir%/%kernel.environment%/customer-login.log'
      formatter: login.log.formatter.line
      level: debug

services:
  login.log.formatter.line:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%] %%channel%%.%%level_name%% %%message%% %%context%% [%%extra.http_method%%, %%extra.url%%, %%extra.ip%%, %%extra.referrer%%, %%extra.user_agent%%]\n"
